# Generated by Django 4.1.3 on 2022-11-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.AddField(
            model_name='card',
            name='accepted',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
