# Generated by Django 4.1.3 on 2022-11-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='gym',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
