# Generated by Django 4.1.3 on 2022-11-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_rename_gym_course_gym'),
        ('coach', '0002_remove_card_user_card_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.gym'),
        ),
        migrations.DeleteModel(
            name='Gym',
        ),
    ]
