# Generated by Django 4.1.3 on 2022-12-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_coach_id_alter_coach_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='Coach',
        ),
    ]
