# Generated by Django 4.1.3 on 2022-12-08 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_alter_coach_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='wrong format enter', regex='09(0[1-2])|(1[0-9])|(3[0-9])|(2[0-1])-?[0-9]{3}-?[0-9]{4}')]),
        ),
    ]
