# Generated by Django 4.1.3 on 2022-11-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_gym_remove_coach_gym_remove_coach_user_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Detaile',
        ),
        migrations.RenameField(
            model_name='detaile',
            old_name='detail',
            new_name='detaile',
        ),
    ]
