# Generated by Django 4.1.3 on 2022-11-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_alter_card_gym_delete_gym'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
