# Generated by Django 4.1.3 on 2022-11-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_rename_detail_detaile_rename_detail_detaile_detaile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detaile',
            new_name='Detail',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='detaile',
            new_name='detail',
        ),
    ]
