# Generated by Django 4.1.3 on 2022-12-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_detail_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='Coach',
        ),
    ]
