# Generated by Django 4.1.3 on 2022-12-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_remove_achievement_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='Coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coach.coach'),
            preserve_default=False,
        ),
    ]
