# Generated by Django 4.1.3 on 2022-11-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_rename_detaile_detail_rename_detaile_detail_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='coach',
        ),
    ]
