# Generated by Django 4.1.3 on 2022-11-29 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_detail_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='fullName',
        ),
        migrations.AlterField(
            model_name='coach',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.coach'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=100)),
                ('Coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.coach')),
            ],
        ),
    ]
