# Generated by Django 4.1.3 on 2022-11-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_remove_coach_fullname_alter_coach_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='year',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
