# Generated by Django 4.1.3 on 2022-12-12 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('writerid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('articleDescription', models.CharField(max_length=250)),
                ('articleContent', models.TextField()),
                ('readDuration', models.CharField(max_length=250)),
                ('writerName', models.CharField(max_length=250)),
                ('articleCategory', models.CharField(max_length=250)),
            ],
        ),
    ]
