# Generated by Django 4.1.3 on 2022-12-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='PicUrl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
