# Generated by Django 4.1.3 on 2022-12-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_picurl_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleCategory',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
