# Generated by Django 4.1.4 on 2022-12-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_isvalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isvalid',
            field=models.BooleanField(null=True),
        ),
    ]
