# Generated by Django 4.1.4 on 2023-01-03 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('PicUrl', models.TextField(null=True)),
                ('likedUserids', models.TextField(null=True)),
                ('comments', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('articleCategory', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=100)),
                ('coachname', models.CharField(max_length=200, null=True)),
                ('coachId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coach.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isliked', models.BooleanField(default=False)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.post')),
                ('usetId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cumment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumment', models.TextField()),
                ('writername', models.CharField(max_length=100)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.post')),
            ],
        ),
    ]
