# Generated by Django 4.1.4 on 2023-01-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_rename_articlecategory_post_postcategoriesid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
