# Generated by Django 4.1.4 on 2023-01-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_post_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='usetId',
            new_name='userId',
        ),
    ]
