# Generated by Django 4.1.3 on 2022-12-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.AlterField(
            model_name='user',
            name='picUrl',
            field=models.TextField(null=True),
        ),
    ]
