# Generated by Django 4.1.3 on 2022-12-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_picture_alter_user_picurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
