# Generated by Django 4.1.3 on 2023-01-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=250)),
                ('writerId', models.IntegerField()),
                ('questionId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('answerId', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=5000)),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=250)),
                ('writerId', models.IntegerField()),
                ('acceptedAnswerId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('questionId', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
