# Generated by Django 4.1.3 on 2023-01-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='acceptedAnswerId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
