# Generated by Django 4.1.3 on 2023-01-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_a', '0002_alter_answer_date_alter_question_acceptedanswerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='category',
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
