# Generated by Django 4.1.3 on 2023-01-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_a', '0003_remove_answer_category_alter_answer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
