# Generated by Django 4.1.3 on 2023-01-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_a', '0004_alter_answer_date_alter_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='acceptedAnswerId',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
