# Generated by Django 4.1.3 on 2022-11-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
