# Generated by Django 4.1.4 on 2022-12-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='articleCategory',
            new_name='CourseCategory',
        ),
    ]
