# Generated by Django 4.1.3 on 2022-12-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_rename_articlecategory_course_coursecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
