# Generated by Django 4.1.4 on 2022-12-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_gym_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='isvalid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='isvalid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='customercard',
            name='isvalid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='isvalid',
            field=models.BooleanField(null=True),
        ),
    ]
