# Generated by Django 4.1.4 on 2022-12-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_customercard'),
        ('gym', '0003_owner_age_owner_description_owner_phone_owner_user'),
    ]

    operations = [
    ]
