# Generated by Django 4.1.4 on 2022-12-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_card_isvalid_course_isvalid_customercard_isvalid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='isvalid',
            field=models.BooleanField(null=True),
        ),
    ]
