# Generated by Django 4.1.4 on 2022-12-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('gym', '0005_rename_custoer_customercard_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercard',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
