# Generated by Django 4.1.4 on 2023-01-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_customercoursecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercoursecard',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.course'),
        ),
    ]
