# Generated by Django 4.1.4 on 2022-12-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_customercard_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='describtion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='gym',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
