# Generated by Django 4.1.4 on 2023-01-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_alter_customercoursecard_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('PicUrl', models.TextField(null=True)),
                ('likedUserids', models.TextField(null=True)),
                ('comments', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
