# Generated by Django 4.1.4 on 2023-01-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_post_articlecategory_post_coachid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Coachname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
