# Generated by Django 4.1.4 on 2023-01-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_post_coachname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Coachname',
            new_name='coachname',
        ),
    ]
